"""add unique constraint to applications

Revision ID: 3119fc789e62
Revises: 3d9649910bcf
Create Date: 2026-04-26 16:32:51.618239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3119fc789e62'
down_revision: Union[str, Sequence[str], None] = '3d9649910bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_job_application', 'applications', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_job_application', 'applications', type_='unique')
    # ### end Alembic commands ###
