"""add resume table and link to applications

Revision ID: 3a32ac39ab09
Revises: aa27ad4bb3e1
Create Date: 2026-05-05 02:09:12.324675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a32ac39ab09'
down_revision: Union[str, Sequence[str], None] = 'aa27ad4bb3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'resume')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
