"""initial schema

Revision ID: 3d9649910bcf
Revises: 
Create Date: 2026-04-24 17:56:01.365675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d9649910bcf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('Applicant', 'Recruiter', name='user_role_enum'), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('resume', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('FRESHER', 'JUNIOR', 'MID', 'SENIOR', name='job_level_enum'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'INTERN', 'CONTRACT', name='employment_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'DRAFT', name='job_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], name='fk_jobs_recruiter_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'company', 'recruiter_id', 'level', 'employment_type', 'is_active', name='unique_active_job_per_recruiter')
    )
    op.create_index('idx_job_search', 'jobs', ['level', 'employment_type', 'is_active', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_token_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SHORTLISTED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='fk_applications_job_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_applications_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_applications_job_id', 'applications', ['job_id'], unique=False)
    op.create_index('idx_applications_user_id', 'applications', ['user_id'], unique=False)
    op.create_table('ai_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('missing_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('strengths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='check_score_range'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name='fk_aiscore_application_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index('idx_aiscore_application_id', 'ai_scores', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_aiscore_application_id', table_name='ai_scores')
    op.drop_table('ai_scores')
    op.drop_index('idx_applications_user_id', table_name='applications')
    op.drop_index('idx_applications_job_id', table_name='applications')
    op.drop_table('applications')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_job_search', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
