"""add resume_id to applications and update resume relationships and add indexes to resumes and applications tables

Revision ID: 44acf2e8bdb4
Revises: 3a32ac39ab09
Create Date: 2026-05-05 21:50:43.173686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44acf2e8bdb4'
down_revision: Union[str, Sequence[str], None] = '3a32ac39ab09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_resumes_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_resumes_user_active', 'resumes', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_resumes_user_id', 'resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.add_column('applications', sa.Column('resume_id', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_applications_resume_id', 'applications', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_applications_resume_id', 'applications', type_='foreignkey')
    op.drop_column('applications', 'resume_id')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index('idx_resumes_user_id', table_name='resumes')
    op.drop_index('idx_resumes_user_active', table_name='resumes')
    op.drop_table('resumes')
    # ### end Alembic commands ###
