"""improve job model structure

Revision ID: 700a5e118d8d
Revises: 5cf323ee623d
Create Date: 2026-05-15 14:03:03.056039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700a5e118d8d'
down_revision: Union[str, Sequence[str], None] = '5cf323ee623d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('resume_match_threshold', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('min_salary', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_salary', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('unique_active_job_per_recruiter'), 'jobs', type_='unique')
    op.drop_index(op.f('idx_job_search'), table_name='jobs')
    op.create_index('idx_job_search', 'jobs', ['status', 'level', 'employment_type', 'created_at'], unique=False)
    op.drop_column('jobs', 'threshold')
    op.drop_column('jobs', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('threshold', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index('idx_job_search', table_name='jobs')
    op.create_index(op.f('idx_job_search'), 'jobs', ['level', 'employment_type', 'is_active', 'created_at'], unique=False)
    op.create_unique_constraint(op.f('unique_active_job_per_recruiter'), 'jobs', ['title', 'company', 'recruiter_id', 'level', 'employment_type', 'is_active'], postgresql_nulls_not_distinct=False)
    op.drop_column('jobs', 'expires_at')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'currency')
    op.drop_column('jobs', 'max_salary')
    op.drop_column('jobs', 'min_salary')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'resume_match_threshold')
    # ### end Alembic commands ###
